config/routes.rb
Rails.application.routes.draw do
  resources :dinosaurs
  resources :matches
  resources :simulations
  resources :abilities
  resources :team_matches
end

app/models/dinosaur.rb
require 'logger'
require 'dinosaurs/fusion'
require 'dinosaurs/battle'
class Dinosaur < ApplicationRecord

  include Dinosaurs::Fusion
  include Dinosaurs::Battle

  belongs_to :left, class_name: 'Dinosaur', optional: true
  belongs_to :right, class_name: 'Dinosaur', optional: true

  # Storage format for abilities
  serialize :abilities
  serialize :abilities_swap_in
  serialize :abilities_counter
  serialize :abilities_on_escape

  # Storage format for resistances
  serialize :resistances

  # Filtering
  scope :filter_by_rarity, -> (rarity) { where rarity: rarity }
  scope :filter_by_is_implemented, -> (is_implemented) { where is_implemented: is_implemented }
  scope :order_by_dna, -> (direction) { order dna: direction }

  def to_param
    name.parameterize
  end

end

app/controllers/dinosaurs_controller.rb
require 'graphviz'

class DinosaursController < ApplicationController
  before_action :set_dinosaur, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /dinosaurs
  # GET /dinosaurs.json
  def index
    @dinosaurs = Dinosaur.where(nil)
    @dinosaurs = @dinosaurs.filter_by_rarity(params[:rarity]) if params[:rarity].present?
    @dinosaurs = @dinosaurs.filter_by_is_implemented(params[:is_implemented]) if params[:is_implemented].present?
    # @dinosaurs = @dinosaurs.order_by_dna(params[:dna]) if params[:dna].present?
    @dinosaurs = @dinosaurs.order(sort_column + " " + sort_direction)
    g = Graphviz::Graph.new
    # Disable for now, this blows up for 245 dinosaurs, and wold not be readable on the page anyway
    # @dinosaurs.map {|dinosaur| add_dinosaur_to_graph(g, dinosaur)}
    @graph = Graphviz::output(g, format: 'svg')
  end

  # GET /dinosaurs/1
  # GET /dinosaurs/1.json
  def show
    # set color based on rarity
    @dinosaur.color = Constants::COLORS[@dinosaur.rarity.to_sym]
    @dinosaur.reset_attributes!
    g = Graphviz::Graph.new
    add_dinosaur_to_graph(g, @dinosaur)
    @graph = Graphviz::output(g, format: 'svg')
    @next_level = @dinosaur.level > 0 ? @dinosaur.level + 1 : Constants::STARTING_LEVELS[@dinosaur.rarity.to_sym]
    @cost = @dinosaur.cost_to_level(@next_level)
  end

  # GET /dinosaurs/new
  def new
    @dinosaur = Dinosaur.new
  end

  # GET /dinosaurs/1/edit
  def edit
  end

  # POST /dinosaurs
  # POST /dinosaurs.json
  def create
    @dinosaur = Dinosaur.new(dinosaur_params)

    respond_to do |format|
      if @dinosaur.save
        format.html { redirect_to @dinosaur, notice: 'Dinosaur was successfully created.' }
        format.json { render :show, status: :created, location: @dinosaur }
      else
        format.html { render :new }
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dinosaurs/1
  # PATCH/PUT /dinosaurs/1.json
  def update
    respond_to do |format|
      if @dinosaur.update(dinosaur_params)
        format.html { redirect_to @dinosaur, notice: 'Dinosaur was successfully updated.' }
        format.json { render :show, status: :ok, location: @dinosaur }
      else
        format.html { render :edit }
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinosaurs/1
  # DELETE /dinosaurs/1.json
  def destroy
    @dinosaur.destroy
    respond_to do |format|
      format.html { redirect_to dinosaurs_url, notice: 'Dinosaur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dinosaur
      @dinosaur = Dinosaur.find_by(slug: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dinosaur_params
      params.require(:dinosaur).permit(:name, :level, :rarity, :health_26, :armor, :critical_chance, :speed, :damage_26, :dna, :left_id, :right_id, :speed_boosts, :health_boosts, :attack_boosts)
    end

    def sort_column
      Dinosaur.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    #COLORS = {common: 'grey', rare: 'blue', epic: 'orange', legendary: 'red', unique: 'green'}

    # add and format a single node if not already on the graph
    # if already on the graph returns the existing node
    # connects if already on the graph and not yet connected
    def add_node(graph, parent, dinosaur, shape='oval')
      # find or insert node into graph, unconnected
      if (node = graph.get_node(node_name(dinosaur)).first)
        parent.connect(node) unless (parent.nil? || parent.connected?(node))
      else
        node = graph.add_node(node_name(dinosaur))
        node.attributes[:id] = dinosaur.id
        node.attributes[:color] = Constants::COLORS[dinosaur.rarity.to_sym]
        node.attributes[:shape] = shape
        node.attributes[:URL] = "/dinosaurs/" + dinosaur.slug
        parent.connect(node) unless parent.nil?
      end
      node
    end

    # add recursivly all possible Hybrids, and recurse upwards
    # TODO: add all components of the hybrids downwards too.
    def node_add_hybrids(graph, node, dinosaur)
      dinosaur.possible_hybrids.each do |hybrid|
        hybrid_node = add_node(graph, nil, hybrid)
        hybrid_node.connect(node) unless hybrid_node.connected?(node)
        # add children of hybrid, unless already connected
        node_add_children(graph, hybrid_node, hybrid)
        node_add_hybrids(graph, hybrid_node, hybrid)
      end
    end

    # add recursivley all children
    # possible cases: child is already in the graph and connected - do nothing
    # child is in the graph, and not connected
    def node_add_children(graph, node, dinosaur)
      if dinosaur.left
        left_node = add_node(graph, node, dinosaur.left)
        node_add_children(graph, left_node, dinosaur.left)
      end
      if dinosaur.right
        right_node = add_node(graph, node, dinosaur.right)
        node_add_children(graph, right_node, dinosaur.right)
      end
    end

    # Add a dinosaur and all connections to the graph
    def add_dinosaur_to_graph(graph, dinosaur)
      node = add_node(graph, nil, dinosaur, 'box')
      node_add_children(graph, node, dinosaur)
      node_add_hybrids(graph, node, dinosaur)
    end

    # generate node name
    def node_name(dinosaur)
      "#{dinosaur.name}\n#{dinosaur.level}"
    end

end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/dinosaurs/_data.html.erb
  <div style="width: 16px; height: 16px; background-color: <%= dinosaur.color %>; display: inline-block;" ></div>
  <big><%= "#{dinosaur.name}" %></big><br/>
  <%= "L: #{dinosaur.level} DNA: #{dinosaur.dna}" %><br/>
  <%= "H: #{dinosaur.health} D: #{dinosaur.damage} S: #{dinosaur.speed_with_boosts} A: #{dinosaur.armor}% C: #{dinosaur.critical_chance}%" %><br/>
  <% Constants::RESISTANCES.each do |resistance| %>
    <%= "#{resistance.to_s.gsub('_',' ').capitalize}: #{dinosaur.resistance(resistance)}, " unless dinosaur.resistance(resistance) == 0 %>
  <% end %>
  <br />
  <%= dinosaur.strategies || dinosaur.strategy%><br/>
  <% if dinosaur.abilities.class == Array %>
  <% dinosaur.abilities.each do |ability| %>
    <a class="modal-trigger" href="#<%= ability.name %>"><%= ability.class %><%= "*" if ability.is_implemented %></a><br/>
    <%= render partial: 'abilities/modal', locals: {ability: ability} %>
  <% end %>
  <% dinosaur.abilities_counter.each do |ability| %>
  <a class="modal-trigger" href="#<%= ability.name %>"><%= ability.class %><%= "*" if ability.is_implemented %></a><br/>
  <%= render partial: 'abilities/modal', locals: {ability: ability} %>
  <% end %>
  <% dinosaur.abilities_swap_in.each do |ability| %>
  <a class="modal-trigger" href="#<%= ability.name %>"><%= ability.class %><%= "*" if ability.is_implemented %></a><br/>
  <%= render partial: 'abilities/modal', locals: {ability: ability} %>
  <% end %>
  <% dinosaur.abilities_on_escape.each do |ability| %>
  <a class="modal-trigger" href="#<%= ability.name %>"><%= ability.class %><%= "*" if ability.is_implemented %></a><br/>
  <%= render partial: 'abilities/modal', locals: {ability: ability} %>
  <% end %>
  <% end %>

app/views/dinosaurs/_form.html.erb
<%= form_with(model: dinosaur, local: true) do |form| %>
  <% if dinosaur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dinosaur.errors.count, "error") %> prohibited this dinosaur from being saved:</h2>

      <ul>
        <% dinosaur.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :rarity %>
    <%= form.select :rarity, ['common', 'rare', 'epic', 'legendary', 'unique'] %>

  </div>

  <div class="field">
    <%= form.label :health_26 %>
    <%= form.number_field :health_26 %>
  </div>
  <div class="field">
    <%= form.label :health_boosts %>
    <%= form.number_field :health_boosts %>
  </div>

  <div class="field">
    <%= form.label :damage_26 %>
    <%= form.number_field :damage_26 %>
  </div>
  <div class="field">
    <%= form.label :attack_boosts %>
    <%= form.number_field :attack_boosts %>
  </div>

  <div class="field">
    <%= form.label :armor %>
    <%= form.number_field :armor %>
  </div>

  <div class="field">
    <%= form.label :critical_chance %>
    <%= form.number_field :critical_chance %>
  </div>

  <div class="field">
    <%= form.label :speed %>
    <%= form.number_field :speed %>
  </div>
  <div class="field">
    <%= form.label :speed_boosts %>
    <%= form.number_field :speed_boosts %>
  </div>

  <div class="field">
    <%= form.label :dna %>
    <%= form.number_field :dna %>
  </div>

  <div class="field">
    <%= form.label :left %>
    <%= form.collection_select :left_id, Dinosaur.all, :id, :name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :right %>
    <%= form.collection_select :right_id, Dinosaur.all, :id, :name, include_blank: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Editing Dinosaur</h1>

<%= render 'form', dinosaur: @dinosaur %>

<%= link_to 'Show', @dinosaur %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dinosaurs</h1>
<div>
</div>

<table>
  <thead>
    <tr>
      <th><%= sortable "name"%></th>
      <th><%= sortable "level" %></th>
      <th><%= sortable "rarity" %></th>
      <th><%= sortable "health" %></th>
      <th><%= sortable "armor" %></th>
      <th><%= sortable "critical_chance" %></th>
      <th><%= sortable "speed" %></th>
      <th><%= sortable "damage" %></th>
      <th><%= sortable "DNA" %></th>
      <th>Abilities</th>
      <th>Swap In</th>
      <th>Counters</th>
      <th>On Escape</th>
      <th>Resistances</th>
      <th>Coins to Create</th>
      <th>DNA to Create</th>
      <th>Left</th>
      <th>Right</th>
      <th>Possible Hybrids</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @dinosaurs.each do |dinosaur| %>
      <tr>
        <td><%= link_to dinosaur.name, dinosaur %><%= "*" if dinosaur.is_implemented %></td>
        <td><%= dinosaur.level %></td>
        <td><%= dinosaur.rarity %></td>
        <td><%= dinosaur.health %></td>
        <td><%= dinosaur.armor %></td>
        <td><%= dinosaur.critical_chance %></td>
        <td><%= dinosaur.speed %></td>
        <td><%= dinosaur.damage %></td>
        <td><%= dinosaur.dna %></td>
        <td><%= dinosaur.abilities %></td>
        <td><%= dinosaur.abilities_swap_in %></td>
        <td><%= dinosaur.abilities_counter %></td>
        <td><%= dinosaur.abilities_on_escape %></td>
        <td><%= dinosaur.resistances %></td>
        <td><%= dinosaur.cost_to_create(:coins) %></td>
        <td><%= dinosaur.cost_to_create(:dna) %></td>
        <td><%= dinosaur.left.name rescue nil %></td>
        <td><%= dinosaur.right.name rescue nil %></td>
        <td><%= dinosaur.possible_hybrid_names %></td>
        <td><%= link_to 'Edit', edit_dinosaur_path(dinosaur) %></td>
        <td><%= link_to 'Destroy', dinosaur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dinosaur', new_dinosaur_path %>
<p>
  <%= @graph.html_safe %>
</p>

app/views/dinosaurs/new.html.erb
<h1>New Dinosaur</h1>

<%= render 'form', dinosaur: @dinosaur %>

<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'dinosaurs/data', dinosaur: @dinosaur %>
<p>
  <strong>Possible Hybrids:</strong>
  <%= @dinosaur.possible_hybrid_names %>
</p>

<p>
  <%= @graph.html_safe %>
</p>

<p>
  <strong>Cost to next level (<%= @next_level%>):</strong><br />
  <div style="display:none;" >
  Coins: <%= @cost[:coins] %><br />
  DNA: <%= @cost[:dna] %><br />
  Fusions: <%= @cost[:fusions] %>
  </div>
<table>
  <thead>
    <td></td>
    <% @cost[:coins].each do |key, value| %>
      <td><%= key %></td>
    <% end %>
  </thead>
  <% @cost.each do |key, cost| %>
    <tr>
      <td><%= key.to_s.capitalize %></td>
      <% cost.each do |key, value| %>
        <td><%= value.to_i > 0 ? value : '' %></td>
      <% end %>
    </tr>
  <% end %>
</table>
</p>
<%= link_to 'Edit', edit_dinosaur_path(@dinosaur) %> |
<%= link_to 'Back', dinosaurs_path %>
<script>
  $('.tabs').tabs();
  $('.modal').modal();
</script>